.Dd May 5, 2023
.Dt git-interactive-sparse-checkout 1
.Os git >=2.25
.
.Sh NAME
.Nm git-interactive-sparse-checkout
.Nd do an interactive sparse checkout
.
.Sh SYNOPSIS
.Nm git-interactive-sparse-checkout
.Ar optional-paths
.Ar to-pre-select
.
.Sh DESCRIPTION
.Nm git-interactive-sparse-checkout
uses a fuzzy file and dir selector to select dirs and files to sparse-checkout
.
.Sh SEE ALSO
.Xr git sparse-checkout 1
